name: PR total changes by christianncode
description: Get the total number of changes in a pull request
author: "Christian Díaz"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token with read access to the repository"
    required: true
    default: ""
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: "check-square"
  color: "green"
