name: PR total changes
description: Get the total number of changes in a pull request
author: "Christian Díaz"
inputs:
  github_token:
    description: "GitHub token with read access to the repository"
    required: true
    default: ""
  additions_limit:
    description: "Maximum number of additions allowed in the PR"
    required: false
    default: ""
  deletions_limit:
    description: "Maximum number of deletions allowed in the PR"
    required: false
    default: ""
  total_limit:
    description: "Total number of changes to consider for the PR"
    required: false
    default: "500"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "check-square"
  color: "green"
